Style/StringLiterals:
  EnforcedStyle: single_quotes
Metrics/LineLength:
  Max: 120 
Metrics/BlockLength:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
